---
name: Check Output Env
on: push

permissions: read-all

jobs:
  test_readability:
    name: Passing Checks
    runs-on: ubuntu-latest
    steps:
      - name: View context attributes
        uses: actions/github-script@v7
        with:
          script: console.log(context)
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: save output
        id: s1
        uses: k1LoW/github-script-ruby@v2
        with:
          script: |
            print("EN1=green\nEN2=red\n")
      - name: check env
        run: echo ${{ steps.s1.outputs.stdout }}
