---
name: "Readability"
on: push

permissions: read-all

jobs:
  test_readability:
    name: Gunning-Fog Index
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Run fog
        run: ruby bin/fog
