---
name: "Readability"
on: push

permissions: read-all

jobs:
  test_readability:
    name: Gunning-Fog Index
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Install Thor
        run: gem install thor --user-install

      - name: Run fog
        run: THOR_SILENCE_DEPRECATION=1 ruby bin/fog index --threshold 0 docs/tests/*
