---
name: Readability
on: push

permissions: read-all

jobs:
  test_readability:
    name: Readability Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install Thor
        run: gem install thor --user-install
      - name: Install Odyssey
        run: gem install odyssey --user-install

      - name: Match docs
        uses: tj-actions/glob@v18
        id: docs
        with:
          match-directories: false
          files: |
            docs/**

      - name: Run Flesch Kincaid
        run: THOR_SILENCE_DEPRECATION=1 ruby bin/readability index ${{ steps.docs.outputs.paths }} --badges >> $GITHUB_ENV

      # adapted from https://github.com/marketplace/actions/dynamic-badges
      - name: Create the FK Badge
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.BADGE_SECRET }}
          gistID: d81400f704f3ba54c9564e038b66c271
          filename: badgeFK.json
          label: Flesch-Kincaid Score
          message: ${{ env.FK_LEGEND }}
          color: ${{ env.FK_COLOUR }}

      - name: Fail if red
        if: ${{ env.FK_COLOUR == 'red' }}
        uses: actions/github-script@v7
        with:
          script: |
            core.setFailed('A red badge for reading ease arose!')
